# Generated by Django 4.2.27 on 2025-12-31 14:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthissue',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='therapyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='therapyimage',
            name='issues',
            field=models.ManyToManyField(related_name='images', to='core.mentalhealthissue'),
        ),
        migrations.AlterField(
            model_name='therapyimage',
            name='max_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='therapyimage',
            name='min_age',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='therapymusic',
            name='audio',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='therapymusic',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='therapymusic',
            name='issues',
            field=models.ManyToManyField(related_name='music', to='core.mentalhealthissue'),
        ),
        migrations.AlterField(
            model_name='therapymusic',
            name='max_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='therapymusic',
            name='min_age',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
