# Generated by Django 4.2.27 on 2025-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='therapy_images/')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('issues', models.ManyToManyField(to='core.mentalhealthissue')),
            ],
        ),
        migrations.CreateModel(
            name='TherapyMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='therapy_music/')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('issues', models.ManyToManyField(to='core.mentalhealthissue')),
            ],
        ),
        migrations.DeleteModel(
            name='TherapyVideo',
        ),
    ]
