# Generated by Django 4.2.27 on 2025-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_therapyimage_therapymusic_delete_therapyvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapyimage',
            name='min_age',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='therapymusic',
            name='min_age',
            field=models.IntegerField(default=7),
        ),
    ]
